# Generated by Django 4.1 on 2023-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0110_remove_channelmanagement_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_room', models.CharField(max_length=100)),
                ('no_of_rooms', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('rental_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rental_rooms',
            },
        ),
    ]
