# Generated by Django 4.1 on 2023-03-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0111_rentalroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalroom',
            name='rental_room',
        ),
        migrations.AddField(
            model_name='rentalroom',
            name='room_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalroom',
            name='rooms',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
