# Generated by Django 4.1 on 2023-03-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0112_remove_rentalroom_rental_room_rentalroom_room_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalRoom',
        ),
    ]
