# Generated by Django 4.1 on 2023-05-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0113_accountsetting_feedback_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(default=None, null=True, upload_to='user_profile_photo'),
        ),
    ]
