# Generated by Django 4.1 on 2023-05-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0114_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicrates',
            name='bookingpal_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='bookingpal_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='rentalsgallery',
            name='bookingpal_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bookingpal_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
