# Generated by Django 4.1 on 2023-04-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0115_rentalbed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbed',
            name='name',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='rentalroom',
            name='name',
            field=models.CharField(max_length=10000),
        ),
    ]
