# Generated by Django 4.1 on 2023-05-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0115_basicrates_bookingpal_id_rental_bookingpal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='bookingpal_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
