# Generated by Django 4.1 on 2023-05-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0116_alter_rentalbed_name_alter_rentalroom_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalBookingRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_checkin_allow', models.CharField(max_length=1000)),
                ('prefered_policy', models.CharField(max_length=1000)),
                ('additional_policy_increase', models.CharField(max_length=1000)),
                ('rates_increase', models.CharField(max_length=1000)),
                ('additional_policy_decrease', models.CharField(max_length=1000)),
                ('rates_decrease', models.CharField(max_length=1000)),
                ('user_id', models.IntegerField()),
                ('rental_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rental_booking_rules',
            },
        ),
    ]
