# Generated by Django 4.1 on 2023-05-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0116_bookings_bookingpal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='bookingpal_img_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
