# Generated by Django 4.1 on 2023-06-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0117_rental_bookingpal_img_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearByAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('distance', models.CharField(default=0, max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'nearby_amenities',
            },
        ),
        migrations.CreateModel(
            name='RentalNearByAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nearbyamenities', models.CharField(max_length=1000)),
                ('distance', models.CharField(default=0, max_length=100)),
                ('user_id', models.IntegerField()),
                ('rental_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rental_nearby_amenities',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='amenities',
            name='code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houserules',
            name='pets_charge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalbasic',
            name='bathrooms',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalbasic',
            name='childs',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalbasic',
            name='living_room',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalbasic',
            name='persons',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalbasic',
            name='rooms',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalbasic',
            name='toilets',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalbasic',
            name='total_beds',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentallocation',
            name='latitude',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentallocation',
            name='longitude',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='channel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rental'),
        ),
    ]
