# Generated by Django 4.1 on 2023-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0117_rentalbookingrules'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=1000)),
                ('account_email_address', models.CharField(max_length=1000)),
                ('prefered_currency', models.CharField(blank=True, max_length=1000, null=True)),
                ('selected_plan', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'account_setting',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('feedback_category', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.BooleanField(default=True)),
                ('blog_updates', models.BooleanField(default=False)),
                ('new_channel_announcement', models.BooleanField(default=True)),
                ('surveys', models.BooleanField(default=True)),
                ('booking_notification', models.BooleanField(default=True)),
                ('payout_notification', models.BooleanField(default=True)),
                ('guest_review', models.BooleanField(default=True)),
                ('guest_notification', models.BooleanField(default=True)),
                ('calendar_update', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
