# Generated by Django 4.1 on 2023-05-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0119_userprofile_birth_date_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='request_booking',
            field=models.BooleanField(default=False),
        ),
    ]
