# Generated by Django 4.1 on 2023-05-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0120_channel_request_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmanagement',
            name='request_booking',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='channelmanagement',
            name='channels',
            field=models.CharField(max_length=1000),
        ),
    ]
