# Generated by Django 4.1 on 2023-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0121_channelmanagement_request_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
