# Generated by Django 4.1 on 2023-05-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0124_rentalnearbyamenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentallocation',
            name='latitude',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentallocation',
            name='longitude',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
