# Generated by Django 4.1 on 2023-05-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0125_rentallocation_latitude_rentallocation_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalbasic',
            name='bathrooms',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalbasic',
            name='childs',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalbasic',
            name='living_room',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalbasic',
            name='persons',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalbasic',
            name='rooms',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalbasic',
            name='toilets',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalbasic',
            name='total_beds',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
