# Generated by Django 4.1 on 2023-06-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0126_rentalbasic_bathrooms_rentalbasic_childs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rental'),
        ),
    ]
