# Generated by Django 4.1 on 2023-06-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0127_alter_bookings_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='created_at',
        ),
    ]
