# Generated by Django 4.1 on 2023-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0128_remove_bookings_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='channel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
