# Generated by Django 4.1 on 2023-06-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0129_alter_bookings_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='houserules',
            name='pets_charge',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
