# Generated by Django 4.1 on 2023-06-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0130_houserules_pets_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houserules',
            name='pets_charge',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
