# Generated by Django 4.1 on 2023-03-21 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0006_alter_rates_price_per_night'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('coupon_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField()),
                ('rooms', models.CharField(max_length=2000)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'be_coupon',
            },
        ),
    ]
