# Generated by Django 4.1 on 2023-03-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0007_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_amount',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
