# Generated by Django 4.1 on 2023-03-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0008_alter_coupon_coupon_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
