# Generated by Django 4.1 on 2023-03-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0009_alter_bookingroom_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
