# Generated by Django 4.1 on 2023-03-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0011_contactinfo_socialmedia_coupon_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalettes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_background_colour', models.CharField(max_length=100)),
                ('top_font_colour', models.CharField(max_length=100)),
                ('footer_background_colour', models.CharField(max_length=100)),
                ('footer_font_colour', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'be_color_palettes',
            },
        ),
        migrations.CreateModel(
            name='widgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'be_widgets',
            },
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='copyright_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='logo',
            field=models.ImageField(default=1, upload_to='be_property_logo'),
            preserve_default=False,
        ),
    ]
