# Generated by Django 4.1 on 2023-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0012_colorpalettes_widgets_contactinfo_copyright_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgets',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='widgets',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
