# Generated by Django 4.1 on 2023-03-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0013_widgets_status_widgets_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='widgets',
            new_name='FooterWidgets',
        ),
    ]
