# Generated by Django 4.1 on 2023-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0015_extraservice_termcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honorific', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('zip_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=500)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('credit_card_number', models.CharField(max_length=100)),
                ('expiry_month', models.CharField(max_length=100)),
                ('expiry_year', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
                ('check_in', models.CharField(max_length=50)),
                ('check_out', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=100)),
                ('no_of_guest', models.CharField(max_length=20)),
                ('no_of_nights', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('tax', models.CharField(max_length=20)),
                ('total_price', models.CharField(max_length=50)),
                ('term_condition', models.BooleanField(default=True)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'be_booking_information',
            },
        ),
        migrations.CreateModel(
            name='RoomAdditionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.CharField(max_length=100)),
                ('checkout_time', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'be_room_additional_details',
            },
        ),
    ]
