# Generated by Django 4.1 on 2023-03-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0016_bookinginformation_roomadditionaldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginformation',
            name='status',
        ),
        migrations.AddField(
            model_name='bookinginformation',
            name='adult',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinginformation',
            name='child',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinginformation',
            name='extra_services',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinginformation',
            name='room_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
